import { useMemo, useState } from 'react'
import {
  Search, Globe2, Network, FileText, Link2, Images, Download, Copy, Check, ExternalLink,
  Camera, ShoppingBag, Newspaper, Video, FileDown, GitCompare, History, Save, RefreshCw,
  AlertTriangle, CheckCircle2, Tags, MonitorSmartphone, ChevronRight
} from 'lucide-react'

const routes = {
  '/website-structure-analyzer': ['Website Structure Analyzer', 'Map pages, navigation, headings, sections and important website information from one public URL.'],
  '/website-link-analyzer': ['Website Link Analyzer', 'Find and organize internal links, external links, PDFs, social links and navigation paths.'],
  '/pdf-link-analyzer': ['PDF Link Analyzer', 'Paste a public PDF URL to extract document metadata, page count, headings, links and a readable text preview.'],
  '/product-page-analyzer': ['Product Page Analyzer', 'Inspect public product pages for product data, prices, images, CTAs, schema and page structure.'],
  '/article-analyzer': ['Article Analyzer', 'Inspect public articles and blog posts for headline, author/date signals, headings, images, links and structure.'],
  '/how-it-works': ['How SiteScope Works', 'SiteScope combines safe public-page crawling with smart browser rendering for selected pages, then organizes the information into a structured report.'],
  '/faq': ['SiteScope FAQ', 'SiteScope analyzes public URLs only. It does not bypass logins, paywalls, CAPTCHAs or access controls. JavaScript rendering is attempted on important pages and falls back safely when unavailable.'],
  '/privacy': ['Privacy Policy', 'Submitted public URLs are processed to produce the requested analysis. SiteScope does not create public indexed result pages from users’ submitted URLs. Browser snapshots saved for change checking are stored in your own browser local storage.'],
  '/terms': ['Terms of Use', 'Use SiteScope lawfully for public web content and websites you are authorized to inspect. Do not use it to bypass access controls or collect restricted information.']
}

function Header(){return <header className="topbar"><a className="brand" href="/"><Network size={21}/> SiteScope</a><nav><a href="/website-analyzer">Analyze</a><a href="/compare-websites">Compare</a><a href="/website-change-monitor">Changes</a><a href="/faq">FAQ</a></nav></header>}
function Footer(){return <footer>© {new Date().getFullYear()} SiteScope · <a href="/privacy">Privacy</a> · <a href="/terms">Terms</a> · <a href="/sitemap.xml">Sitemap</a></footer>}
function Shell({children}){return <div className="app"><Header/><main>{children}</main><Footer/></div>}
function Card({icon:Icon,title,text,href}){const body=<><Icon size={23}/><h3>{title}</h3><p>{text}</p>{href&&<span className="learn">Open <ChevronRight size={15}/></span>}</>;return href?<a className="card linked" href={href}>{body}</a>:<article className="card">{body}</article>}
function Panel({title,children,className=''}){return <section className={`panel ${className}`}><h3>{title}</h3>{children}</section>}
function Info({label,value}){return <div className="info"><b>{label}</b><span className="break">{String(value ?? '')}</span></div>}
function Empty({children='Nothing detected.'}){return <p className="muted">{children}</p>}
function Stat({n,t}){return <div><b>{n ?? 0}</b><span>{t}</span></div>}
function Pill({children}){return <span className="tag">{children}</span>}
function LinkRow({href,children}){return <a className="row break" href={href} target="_blank" rel="noreferrer">{children || href}</a>}

async function analyzeUrl(url,maxPages=10){
 const r=await fetch('/api/analyze',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({url,maxPages:Number(maxPages)})})
 const b=await r.json(); if(!r.ok)throw new Error(b.error||'Analysis failed'); return b
}
function exportJson(data,name='sitescope-analysis.json'){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'}));a.download=name;a.click();URL.revokeObjectURL(a.href)}
function summarizeSnapshot(d){if(d.kind!=='website')return d;return{kind:d.kind,analyzedAt:d.analyzedAt,url:d.finalHomeUrl,site:d.site,totals:d.totals,navigation:d.navigation,structure:d.structure,grouped:{summary:d.grouped?.summary,pricing:d.grouped?.pricing,products:d.grouped?.products,articles:d.grouped?.articles,technologies:d.grouped?.technologies,seoIssues:d.grouped?.seoIssues},pages:d.pages?.map(p=>({url:p.url,title:p.title,description:p.description,type:p.type,wordCount:p.wordCount,headings:p.headings,prices:p.prices,ctas:p.ctas,images:p.images?.map(i=>i.src)}))}}
function snapshotDiff(oldD,newD){
 const oldPages=new Map((oldD?.structure||[]).map(x=>[x.url,x]));const newPages=new Map((newD?.structure||[]).map(x=>[x.url,x]));
 const added=[...newPages.keys()].filter(x=>!oldPages.has(x));const removed=[...oldPages.keys()].filter(x=>!newPages.has(x));
 const changed=[];const op=new Map((oldD?.pages||[]).map(x=>[x.url,x]));const np=new Map((newD?.pages||[]).map(x=>[x.url,x]));
 for(const [url,p] of np){const o=op.get(url);if(!o)continue;const fields=[];if(o.title!==p.title)fields.push('title');if(o.description!==p.description)fields.push('description');if(JSON.stringify(o.prices)!==JSON.stringify(p.prices))fields.push('prices');if(JSON.stringify(o.headings)!==JSON.stringify(p.headings))fields.push('headings');if(fields.length)changed.push({url,fields})}
 return{added,removed,changed,oldDate:oldD?.analyzedAt,newDate:newD?.analyzedAt}
}

function UniversalAnalyzer({compact=false,initialTab='Overview'}){
 const [url,setUrl]=useState('');const [maxPages,setMaxPages]=useState(10);const [data,setData]=useState(null);const [loading,setLoading]=useState(false);const [error,setError]=useState('');const [tab,setTab]=useState(initialTab);const [copied,setCopied]=useState(false)
 async function run(e){e?.preventDefault();if(!url.trim())return;setLoading(true);setError('');setData(null);try{const b=await analyzeUrl(url,maxPages);setData(b);setTab(b.kind==='website'?'Overview':'Document')}catch(err){setError(err.message)}finally{setLoading(false)}}
 async function copy(){await navigator.clipboard.writeText(JSON.stringify(data,null,2));setCopied(true);setTimeout(()=>setCopied(false),1200)}
 return <>
 <section className={`hero analyzer-hero ${compact?'compact':''}`}><span className="eyebrow">UNIVERSAL PUBLIC LINK ANALYZER</span><h1>{compact?'Analyze a public link.':<>Paste a public link.<br/><em>See what is really inside.</em></>}</h1><p>Websites, JavaScript-heavy pages, products, articles, PDFs and public video pages — SiteScope detects the link type and organizes the important information.</p>
 <form className="search" onSubmit={run}><Globe2 size={21}/><input inputMode="url" autoCapitalize="none" autoCorrect="off" value={url} onChange={e=>setUrl(e.target.value)} placeholder="Paste website, product, article or PDF link"/><select aria-label="Pages to scan" value={maxPages} onChange={e=>setMaxPages(e.target.value)}><option value="5">5 pages</option><option value="10">10 pages</option><option value="15">15 pages</option></select><button disabled={loading||!url.trim()}><Search size={18}/>{loading?'Analyzing…':'Analyze link'}</button></form>{error&&<div className="error"><AlertTriangle size={18}/>{error}</div>}</section>
 {!data&&!loading&&!compact&&<FeatureGrid/>}
 {loading&&<div className="loading"><RefreshCw size={20} className="spin"/> Rendering, crawling and organizing the link…</div>}
 {data&&<Result data={data} tab={tab} setTab={setTab} copy={copy} copied={copied}/>}</>
}
function FeatureGrid(){return <section className="cards feature-grid"><Card icon={MonitorSmartphone} title="Rendered websites" text="Attempts a real browser render for important JavaScript-heavy pages."/><Card icon={Camera} title="Visual snapshot" text="Captures the visible homepage and maps rendered sections."/><Card icon={Tags} title="Smart grouping" text="Groups products, pricing, CTAs, FAQs, contacts, policies and technologies."/><Card icon={FileDown} title="PDF links" text="Reads public PDF metadata, headings, links and text preview."/><Card icon={ShoppingBag} title="Products" text="Detects Product schema, prices, brand, images and selling actions."/><Card icon={Newspaper} title="Articles" text="Detects article metadata, headline, author/date signals and structure."/><Card icon={Video} title="Video intelligence" text="Finds embedded/direct videos and public caption tracks when exposed."/><Card icon={GitCompare} title="Compare & changes" text="Compare two links or save a local snapshot and see what changed later."/></section>}
function Result({data,tab,setTab,copy,copied}){
 if(data.kind==='pdf')return <DocumentResult data={data}/>
 if(data.kind==='video')return <DirectVideoResult data={data}/>
 const tabs=['Overview','Visual','Pages','Images','Products & Articles','Media & PDFs','SEO','Technical']
 return <section className="results"><div className="resulthead"><div><span className="eyebrow">ANALYSIS COMPLETE · {data.site.detectedPrimaryType?.toUpperCase()}</span><h2>{data.site.title||data.site.hostname}</h2><a href={data.finalHomeUrl} target="_blank" rel="noreferrer">{data.site.hostname} <ExternalLink size={13}/></a></div><div className="actions"><button onClick={copy}>{copied?<Check size={16}/>:<Copy size={16}/>} {copied?'Copied':'Copy JSON'}</button><button onClick={()=>exportJson(data,`${data.site.hostname}-sitescope.json`)}><Download size={16}/> Export</button></div></div>
 <div className="stats"><Stat n={data.totals.pages} t="Pages"/><Stat n={data.totals.images} t="Images"/><Stat n={data.totals.videos} t="Videos"/><Stat n={data.totals.words} t="Words"/></div>
 <div className="capabilities"><span className={data.capabilities?.browserRendering?'ok':'soft'}>{data.capabilities?.browserRendering?<CheckCircle2 size={15}/>:<AlertTriangle size={15}/>} Browser render: {data.capabilities?.browserRendering?`${data.capabilities.renderedPages} pages`:'fallback mode'}</span><span className={data.screenshot?'ok':'soft'}><Camera size={15}/> Visual snapshot: {data.screenshot?'captured':'not available'}</span></div>
 <div className="tabs">{tabs.map(x=><button className={tab===x?'active':''} onClick={()=>setTab(x)} key={x}>{x}</button>)}</div>
 {tab==='Overview'&&<Overview data={data}/>} {tab==='Visual'&&<Visual data={data}/>} {tab==='Pages'&&<Pages data={data}/>} {tab==='Images'&&<ImageGallery images={data.grouped.images}/>} {tab==='Products & Articles'&&<CommerceContent data={data}/>} {tab==='Media & PDFs'&&<Media data={data}/>} {tab==='SEO'&&<Seo data={data}/>} {tab==='Technical'&&<Technical data={data}/>}</section>
}
function Overview({data}){const g=data.grouped||{};return <><div className="grid"><Panel title="What this website appears to be about"><p className="lead-copy">{data.site.summary||'No clear summary was exposed by the site.'}</p>{(g.purposeSignals||[]).map((x,i)=><div className="signal" key={i}>{x}</div>)}</Panel><Panel title="Important details"><Info label="Primary type" value={data.site.detectedPrimaryType}/><Info label="Language" value={data.site.language||'Not declared'}/><Info label="Pages scanned" value={data.totals.pages}/><Info label="Rendered pages" value={data.capabilities?.renderedPages||0}/><Info label="Canonical" value={data.site.canonical||'Not declared'}/></Panel></div>
 <div className="grid three"><Panel title={`Pricing (${g.pricing?.length||0})`}>{g.pricing?.length?g.pricing.map(x=><Pill key={x}>{x}</Pill>):<Empty/>}</Panel><Panel title={`Main CTAs (${g.ctas?.length||0})`}>{g.ctas?.length?g.ctas.slice(0,12).map((x,i)=><div className="row" key={i}>{x.text}</div>):<Empty/>}</Panel><Panel title="Contacts & socials">{g.contacts?.emails?.map(x=><div className="row" key={x}>{x}</div>)}{g.contacts?.phones?.map(x=><div className="row" key={x}>{x}</div>)}{g.contacts?.socials?.slice(0,8).map(x=><LinkRow href={x} key={x}/>) }{!g.contacts?.emails?.length&&!g.contacts?.phones?.length&&!g.contacts?.socials?.length&&<Empty/>}</Panel></div>
 <div className="grid"><Panel title={`Main navigation (${data.navigation.length})`}>{data.navigation.length?data.navigation.slice(0,30).map((x,i)=><LinkRow key={i} href={x.url}>{x.text||x.url}</LinkRow>):<Empty/>}</Panel><Panel title={`FAQs (${g.faqs?.length||0})`}>{g.faqs?.length?g.faqs.slice(0,10).map((x,i)=><details className="faqrow" key={i}><summary>{x.question}</summary><p>{x.answer||'Answer text not clearly exposed.'}</p></details>):<Empty/>}</Panel></div></>}
function Visual({data}){const sections=data.pages?.find(p=>p.rendered)?.sections||[];return <div className="grid visual-grid"><Panel title="Rendered page snapshot" className="screenshot-panel">{data.screenshot?<img className="site-shot" src={data.screenshot} alt="Rendered website snapshot"/>:<Empty>Browser snapshot was not available. The crawler report still works in fallback mode.</Empty>}</Panel><Panel title={`Detected visual sections (${sections.length})`}>{sections.length?sections.map((s,i)=><div className="sectionrow" key={i}><b>{s.heading||`${s.tag} section`}</b><small>{s.y}px from top · {s.height}px tall</small><p>{s.text}</p></div>):<Empty>No rendered DOM sections were available.</Empty>}</Panel></div>}
function Pages({data}){return <div className="pages">{data.pages.map((p,i)=><article className="page" key={p.url}><div className="page-top"><small>PAGE {i+1} · {p.type.toUpperCase()}</small>{p.rendered&&<Pill>browser-rendered</Pill>}</div><h3>{p.title||'Untitled page'}</h3><LinkRow href={p.url}/><p>{p.summary||p.description||'No summary exposed.'}</p><div className="mini"><span>{p.wordCount} words</span><span>{p.images.length} images</span><span>{p.ctas.length} CTAs</span><span>{p.forms.length} forms</span></div>{p.headings.h1.length>0&&<div className="heading-list"><b>H1</b>{p.headings.h1.map(x=><span key={x}>{x}</span>)}</div>}{p.headings.h2.length>0&&<div className="heading-list"><b>H2</b>{p.headings.h2.slice(0,12).map(x=><span key={x}>{x}</span>)}</div>}{p.prices.length>0&&<div className="pillline">{p.prices.map(x=><Pill key={x}>{x}</Pill>)}</div>}</article>)}</div>}
function ImageGallery({images=[]}){return <Panel title={`Discovered images (${images.length})`}><div className="images">{images.length?images.map((x,i)=><a className="image-card" href={x.src} target="_blank" rel="noreferrer" key={`${x.src}-${i}`}><div className="image-box"><img src={x.src} loading="lazy" alt={x.alt||'Discovered website asset'} onError={e=>{e.currentTarget.style.display='none'}}/></div><div className="image-meta"><b>{x.alt||'No alt text'}</b><span>{x.kind||'content'}{x.width?` · ${x.width}×${x.height||'?'}`:''}</span><small>{x.sourcePage}</small></div></a>):<Empty>No public images detected.</Empty>}</div></Panel>}
function CommerceContent({data}){const g=data.grouped||{};return <div className="grid"><Panel title={`Products (${g.products?.length||0})`}>{g.products?.length?g.products.map((p,i)=><div className="object-card" key={i}><b>{p.name||'Product'}</b>{p.brand&&<span>Brand: {p.brand}</span>}{p.price&&<span>Price: {p.price} {p.currency}</span>}{p.availability&&<small>{p.availability}</small>}{p.url&&<LinkRow href={p.url}>Open product source</LinkRow>}</div>):<Empty>No Product structured data was detected on scanned pages.</Empty>}</Panel><Panel title={`Articles (${g.articles?.length||0})`}>{g.articles?.length?g.articles.map((a,i)=><div className="object-card" key={i}><b>{a.headline||'Article'}</b>{a.author&&<span>Author: {a.author}</span>}{a.datePublished&&<span>Published: {a.datePublished}</span>}{a.url&&<LinkRow href={a.url}>Open article source</LinkRow>}</div>):<Empty>No Article structured data was detected on scanned pages.</Empty>}</Panel></div>}
function Media({data}){const g=data.grouped||{};return <><div className="grid"><Panel title={`Videos (${g.videos?.length||0})`}>{g.videos?.length?g.videos.map((v,i)=><div className="object-card" key={i}>{v.poster&&<img className="poster" src={v.poster} alt="Video poster"/>}<b>{v.provider||'video'}</b><LinkRow href={v.url}>{v.url}</LinkRow>{v.tracks?.length>0&&<span>{v.tracks.length} caption/subtitle track(s)</span>}</div>):<Empty>No embedded/public videos detected.</Empty>}</Panel><Panel title={`Public PDF links (${g.pdfs?.length||0})`}>{g.pdfs?.length?g.pdfs.map(x=><LinkRow href={x} key={x}/>):<Empty/>}</Panel></div><Panel title={`Caption transcripts (${data.captions?.filter(x=>x.transcript).length||0})`}>{data.captions?.some(x=>x.transcript)?data.captions.filter(x=>x.transcript).map((x,i)=><div className="transcript" key={i}><b>{x.label||x.kind||'Caption track'}</b><p>{x.transcript}</p></div>):<Empty>Captions were not publicly exposed in a readable track on the scanned pages.</Empty>}</Panel></>}
function Seo({data}){const g=data.grouped||{};return <div className="grid"><Panel title={`SEO checks (${g.seoIssues?.length||0})`}>{g.seoIssues?.length?g.seoIssues.map((x,i)=><div className="issue" key={i}><AlertTriangle size={16}/><div><b>{x.issue}</b><small>{x.page}</small></div></div>):<div className="success"><CheckCircle2 size={18}/> No basic issues detected on the scanned pages.</div>}</Panel><Panel title="SEO signals"><Info label="robots.txt" value={data.robots.found?'Found':'Not found'}/><Info label="Sitemaps declared" value={data.robots.sitemaps.length}/><Info label="Canonical" value={data.site.canonical||'Not declared'}/><Info label="Structured types" value={[...new Set(data.pages.flatMap(p=>p.structuredDataTypes))].join(', ')||'None detected'}/></Panel></div>}
function Technical({data}){const g=data.grouped||{};return <><div className="grid"><Panel title="Technology signals">{g.technologies?.length?g.technologies.map(x=><Pill key={x}>{x}</Pill>):<Empty/>}</Panel><Panel title="Crawl details"><Info label="Origin" value={data.site.origin}/><Info label="Internal links" value={data.totals.internalLinks}/><Info label="External links" value={data.totals.externalLinks}/><Info label="Skipped URLs" value={data.skipped.length}/><Info label="Browser renderer" value={data.capabilities?.browserRendering?'Used':'Fallback crawler'}/></Panel></div>{data.skipped.length>0&&<Panel title="Skipped URLs">{data.skipped.slice(0,50).map((x,i)=><div className="row" key={i}><b>{x.reason}</b><span className="break">{x.url}</span></div>)}</Panel>}</>}
function DocumentResult({data}){return <section className="results"><div className="resulthead"><div><span className="eyebrow">PDF ANALYSIS COMPLETE</span><h2>{data.title||'PDF document'}</h2><LinkRow href={data.url}>{data.url}</LinkRow></div><div className="actions"><button onClick={()=>exportJson(data,'sitescope-pdf-analysis.json')}><Download size={16}/> Export</button></div></div><div className="stats"><Stat n={data.pages} t="PDF pages"/><Stat n={data.words} t="Words"/><Stat n={data.headings?.length} t="Headings"/><Stat n={data.links?.length} t="Links"/></div><div className="grid"><Panel title="Document overview"><Info label="Title" value={data.title}/><Info label="Author" value={data.author||'Not declared'}/><Info label="Subject" value={data.subject||'Not declared'}/><p>{data.summary}</p></Panel><Panel title="Detected headings">{data.headings?.length?data.headings.map(x=><div className="row" key={x}>{x}</div>):<Empty/>}</Panel></div><div className="grid"><Panel title="Links">{data.links?.length?data.links.map(x=><LinkRow href={x} key={x}/>):<Empty/>}</Panel><Panel title="Text preview"><p className="text-preview">{data.textPreview}</p></Panel></div></section>}
function DirectVideoResult({data}){return <section className="results"><div className="resulthead"><div><span className="eyebrow">DIRECT VIDEO DETECTED</span><h2>Public video file</h2><LinkRow href={data.url}>{data.url}</LinkRow></div></div><div className="grid"><Panel title="Video file information"><Info label="Content type" value={data.contentType}/><Info label="Size" value={data.sizeBytes?`${Math.round(data.sizeBytes/1024/1024*10)/10} MB`:'Not declared'}/><Info label="Provider" value={data.provider}/></Panel><Panel title="Understanding level"><p>{data.note}</p></Panel></div></section>}

function ComparePage(){const [a,setA]=useState('');const [b,setB]=useState('');const [maxPages,setMaxPages]=useState(5);const [left,setLeft]=useState(null);const [right,setRight]=useState(null);const [loading,setLoading]=useState(false);const [error,setError]=useState('');async function run(e){e.preventDefault();setLoading(true);setError('');try{const [x,y]=await Promise.all([analyzeUrl(a,maxPages),analyzeUrl(b,maxPages)]);setLeft(x);setRight(y)}catch(err){setError(err.message)}finally{setLoading(false)}}const comp=useMemo(()=>left&&right&&left.kind==='website'&&right.kind==='website'?compareReports(left,right):null,[left,right]);return <Shell><section className="hero compact"><span className="eyebrow">COMPARE TWO PUBLIC LINKS</span><h1>Compare websites side by side.</h1><p>Analyze two links and compare structure, pages, content, images, products, pricing, technologies and SEO signals.</p><form className="compare-form" onSubmit={run}><input inputMode="url" value={a} onChange={e=>setA(e.target.value)} placeholder="First website URL"/><input inputMode="url" value={b} onChange={e=>setB(e.target.value)} placeholder="Second website URL"/><select value={maxPages} onChange={e=>setMaxPages(e.target.value)}><option value="5">5 pages each</option><option value="10">10 pages each</option></select><button disabled={loading||!a||!b}><GitCompare size={18}/>{loading?'Comparing…':'Compare links'}</button></form>{error&&<div className="error">{error}</div>}</section>{comp&&<Comparison comp={comp} left={left} right={right}/>}</Shell>}
function compareReports(a,b){return{metrics:[['Pages',a.totals.pages,b.totals.pages],['Images',a.totals.images,b.totals.images],['Videos',a.totals.videos,b.totals.videos],['Words',a.totals.words,b.totals.words],['SEO issues',a.grouped.seoIssues.length,b.grouped.seoIssues.length],['Products',a.grouped.products.length,b.grouped.products.length]],onlyA:a.structure.filter(x=>!b.structure.some(y=>new URL(y.url).pathname===new URL(x.url).pathname)).slice(0,30),onlyB:b.structure.filter(x=>!a.structure.some(y=>new URL(y.url).pathname===new URL(x.url).pathname)).slice(0,30),techA:a.grouped.technologies,techB:b.grouped.technologies,pricingA:a.grouped.pricing,pricingB:b.grouped.pricing}}
function Comparison({comp,left,right}){return <section className="results"><div className="compare-head"><h2>{left.site.hostname}</h2><span>VS</span><h2>{right.site.hostname}</h2></div><div className="compare-table">{comp.metrics.map(([name,a,b])=><div className="compare-row" key={name}><b>{a}</b><span>{name}</span><b>{b}</b></div>)}</div><div className="grid"><Panel title={`${left.site.hostname} unique paths`}>{comp.onlyA.length?comp.onlyA.map(x=><div className="row" key={x.url}>{new URL(x.url).pathname}</div>):<Empty/>}</Panel><Panel title={`${right.site.hostname} unique paths`}>{comp.onlyB.length?comp.onlyB.map(x=><div className="row" key={x.url}>{new URL(x.url).pathname}</div>):<Empty/>}</Panel></div><div className="grid"><Panel title={`${left.site.hostname} technologies`}>{comp.techA.map(x=><Pill key={x}>{x}</Pill>)}</Panel><Panel title={`${right.site.hostname} technologies`}>{comp.techB.map(x=><Pill key={x}>{x}</Pill>)}</Panel></div><div className="grid"><Panel title={`${left.site.hostname} pricing`}>{comp.pricingA.map(x=><Pill key={x}>{x}</Pill>)}</Panel><Panel title={`${right.site.hostname} pricing`}>{comp.pricingB.map(x=><Pill key={x}>{x}</Pill>)}</Panel></div></section>}

function ChangePage(){const [url,setUrl]=useState('');const [current,setCurrent]=useState(null);const [previous,setPrevious]=useState(null);const [diff,setDiff]=useState(null);const [loading,setLoading]=useState(false);const [error,setError]=useState('');async function check(e){e.preventDefault();setLoading(true);setError('');try{const d=await analyzeUrl(url,10);if(d.kind!=='website')throw new Error('Change snapshots currently support website pages.');const key=`sitescope:snapshot:${new URL(d.finalHomeUrl).hostname}`;const old=JSON.parse(localStorage.getItem(key)||'null');const snap=summarizeSnapshot(d);setPrevious(old);setCurrent(snap);setDiff(old?snapshotDiff(old,snap):null)}catch(err){setError(err.message)}finally{setLoading(false)}}function save(){if(!current)return;localStorage.setItem(`sitescope:snapshot:${new URL(current.url).hostname}`,JSON.stringify(current));setPrevious(current);setDiff(null)}return <Shell><section className="hero compact"><span className="eyebrow">LOCAL WEBSITE CHANGE CHECKER</span><h1>See what changed since your last scan.</h1><p>SiteScope stores the saved snapshot in this browser only. Re-scan later to compare page additions/removals and important content changes.</p><form className="search monitor-search" onSubmit={check}><History size={20}/><input inputMode="url" value={url} onChange={e=>setUrl(e.target.value)} placeholder="Website URL to check"/><button disabled={loading||!url}><RefreshCw size={18}/>{loading?'Checking…':'Check changes'}</button></form>{error&&<div className="error">{error}</div>}</section>{current&&<section className="results"><div className="resulthead"><div><h2>{new URL(current.url).hostname}</h2><p>{previous?'Previous snapshot found in this browser.':'No previous snapshot found yet.'}</p></div><div className="actions"><button onClick={save}><Save size={16}/> Save current snapshot</button></div></div>{diff?<><div className="stats"><Stat n={diff.added.length} t="Pages added"/><Stat n={diff.removed.length} t="Pages removed"/><Stat n={diff.changed.length} t="Pages changed"/><Stat n={current.totals?.pages} t="Pages now"/></div><div className="grid three"><Panel title="Added pages">{diff.added.length?diff.added.map(x=><div className="row break" key={x}>{x}</div>):<Empty/>}</Panel><Panel title="Removed pages">{diff.removed.length?diff.removed.map(x=><div className="row break" key={x}>{x}</div>):<Empty/>}</Panel><Panel title="Content changes">{diff.changed.length?diff.changed.map(x=><div className="object-card" key={x.url}><b>{x.fields.join(', ')}</b><small>{x.url}</small></div>):<Empty/>}</Panel></div></>:<Panel title="Ready to start monitoring"><p>Save this scan as your baseline. When you return on this same browser and run another scan, SiteScope will compare it against this snapshot.</p></Panel>}</section>}</Shell>}

function StaticPage({title,text}){return <Shell><section className="hero simple compact"><span className="eyebrow">PUBLIC LINK INTELLIGENCE</span><h1>{title}</h1><p>{text}</p><a className="cta" href="/website-analyzer">Analyze a public link →</a></section><section className="cards"><Card icon={MonitorSmartphone} title="Browser rendering" text="Important pages can be rendered before extraction."/><Card icon={FileDown} title="Multiple link types" text="Website pages, products, articles and public PDFs."/><Card icon={GitCompare} title="Compare and track" text="Compare two sites or save local change snapshots."/></section></Shell>}
function Home(){return <Shell><UniversalAnalyzer/><section className="tool-links"><h2>More SiteScope tools</h2><div className="cards"><Card href="/website-structure-analyzer" icon={Network} title="Structure analyzer" text="Pages, hierarchy, headings and navigation."/><Card href="/product-page-analyzer" icon={ShoppingBag} title="Product analyzer" text="Products, prices, schema and images."/><Card href="/pdf-link-analyzer" icon={FileDown} title="PDF analyzer" text="Public PDF text, metadata and links."/><Card href="/compare-websites" icon={GitCompare} title="Compare websites" text="Run two analyses side by side."/></div></section></Shell>}
function AnalyzerPage(){return <Shell><UniversalAnalyzer compact/></Shell>}
export default function App(){const p=window.location.pathname.replace(/\/+$/,'')||'/';if(p==='/')return <Home/>;if(['/website-analyzer','/pdf-link-analyzer','/product-page-analyzer','/article-analyzer'].includes(p))return <AnalyzerPage/>;if(p==='/compare-websites')return <ComparePage/>;if(p==='/website-change-monitor')return <ChangePage/>;if(routes[p])return <StaticPage title={routes[p][0]} text={routes[p][1]}/>;return <StaticPage title="Page not found" text="Return to SiteScope or open the universal analyzer."/>}
