import { useMemo, useState } from 'react'
import { Search, Globe2, Network, FileText, Link2, Images, Download, Copy, Check, ExternalLink } from 'lucide-react'

const routes = {
  '/': ['See how a website is structured in seconds.','Paste a public URL and SiteScope organizes pages, navigation, headings, links, images and metadata.'],
  '/website-structure-analyzer': ['Website Structure Analyzer','Map public pages, navigation and headings from one URL.'],
  '/website-link-analyzer': ['Website Link Analyzer','Separate internal and external links from public website pages.'],
  '/how-it-works': ['How SiteScope works','SiteScope follows permitted same-site HTML pages, respects robots.txt and organizes what it finds.'],
  '/faq': ['Website Analyzer FAQ','SiteScope analyzes public pages only, does not bypass logins or paywalls, and caps each crawl at 20 pages.'],
  '/privacy': ['Privacy Policy','Submitted URLs are used to produce the requested analysis. No public result page is created for submitted websites.'],
  '/terms': ['Terms of Use','Use SiteScope lawfully for public web content and websites you are authorized to inspect.']
}

function Header(){return <header><a className="brand" href="/"><Network size={20}/> SiteScope</a><nav><a href="/website-analyzer">Analyzer</a><a href="/how-it-works">How it works</a><a href="/faq">FAQ</a></nav></header>}
function Footer(){return <footer>© {new Date().getFullYear()} SiteScope · <a href="/privacy">Privacy</a> · <a href="/terms">Terms</a> · <a href="/sitemap.xml">Sitemap</a></footer>}
function Shell({children}){return <div className="app"><Header/><main>{children}</main><Footer/></div>}
function StaticPage({title,text}){return <Shell><section className="hero simple"><span className="eyebrow">PUBLIC WEBSITE ANALYSIS</span><h1>{title}</h1><p>{text}</p><a className="cta" href="/website-analyzer">Open website analyzer →</a></section><section className="cards"><Card icon={Network} title="Structure" text="Pages, paths and navigation in a readable order."/><Card icon={FileText} title="Content" text="Titles, descriptions and headings from analyzed pages."/><Card icon={Link2} title="Links" text="Internal and external links separated clearly."/></section></Shell>}
function Card({icon:Icon,title,text}){return <article className="card"><Icon size={22}/><h3>{title}</h3><p>{text}</p></article>}

function Analyzer(){
 const [url,setUrl]=useState(''); const [maxPages,setMaxPages]=useState(10); const [data,setData]=useState(null); const [loading,setLoading]=useState(false); const [error,setError]=useState(''); const [tab,setTab]=useState('Overview'); const [copied,setCopied]=useState(false)
 const internal=useMemo(()=>data?[...new Set(data.pages.flatMap(p=>p.internalLinks))]:[],[data]); const external=useMemo(()=>data?[...new Set(data.pages.flatMap(p=>p.externalLinks))]:[],[data]); const imgs=useMemo(()=>data?[...new Set(data.pages.flatMap(p=>p.images))]:[],[data])
 async function run(e){e.preventDefault();setLoading(true);setError('');setData(null);try{const r=await fetch('/api/analyze',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({url,maxPages:Number(maxPages)})});const b=await r.json();if(!r.ok)throw new Error(b.error||'Analysis failed');setData(b)}catch(err){setError(err.message)}finally{setLoading(false)}}
 async function copy(){await navigator.clipboard.writeText(JSON.stringify(data,null,2));setCopied(true);setTimeout(()=>setCopied(false),1200)}
 function download(){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'}));a.download=`${data.site.hostname}-analysis.json`;a.click();URL.revokeObjectURL(a.href)}
 return <Shell><section className="hero"><span className="eyebrow">PUBLIC WEBSITE STRUCTURE ANALYZER</span><h1>Analyze a website.<br/><em>See what is inside.</em></h1><p>Paste a public URL. SiteScope organizes permitted pages, navigation, headings, links, images and technical metadata.</p><form className="search" onSubmit={run}><Globe2 size={20}/><input value={url} onChange={e=>setUrl(e.target.value)} placeholder="example.com"/><select value={maxPages} onChange={e=>setMaxPages(e.target.value)}><option>5</option><option>10</option><option>15</option><option>20</option></select><button disabled={loading||!url.trim()}><Search size={18}/>{loading?'Analyzing…':'Analyze'}</button></form>{error&&<div className="error">{error}</div>}</section>
 {!data&&!loading&&<section className="cards"><Card icon={Network} title="Site structure" text="Discover same-site pages and navigation."/><Card icon={FileText} title="Content outline" text="Titles, descriptions and H1–H3 headings."/><Card icon={Link2} title="Links" text="Separate internal and external links."/><Card icon={Images} title="Images" text="List image URLs and technical metadata."/></section>}
 {loading&&<div className="loading">Crawling and organizing the website…</div>}
 {data&&<section className="results"><div className="resulthead"><div><span className="eyebrow">ANALYSIS COMPLETE</span><h2>{data.site.title||data.site.hostname}</h2><a href={data.finalHomeUrl} target="_blank" rel="noreferrer">{data.site.hostname} <ExternalLink size={13}/></a></div><div className="actions"><button onClick={copy}>{copied?<Check size={16}/>:<Copy size={16}/>} {copied?'Copied':'Copy JSON'}</button><button onClick={download}><Download size={16}/> Export JSON</button></div></div><div className="stats"><Stat n={data.totals.pages} t="Pages"/><Stat n={data.totals.internalLinks} t="Internal links"/><Stat n={data.totals.externalLinks} t="External links"/><Stat n={data.totals.images} t="Images"/></div><div className="tabs">{['Overview','Structure','Pages','Links','Images','Technical'].map(x=><button className={tab===x?'active':''} onClick={()=>setTab(x)} key={x}>{x}</button>)}</div>
 {tab==='Overview'&&<div className="grid"><Panel title="Website overview"><Info label="Title" value={data.site.title||'Not found'}/><Info label="Description" value={data.site.description||'Not found'}/><Info label="Language" value={data.site.language||'Not declared'}/><Info label="Canonical" value={data.site.canonical||'Not found'}/></Panel><Panel title="Main navigation">{data.navigation.length?data.navigation.map((x,i)=><a className="row" key={i} href={x.url} target="_blank" rel="noreferrer">{x.text}</a>):<p>No navigation links detected.</p>}</Panel></div>}
 {tab==='Structure'&&<Panel title="Website structure">{data.structure.map((p,i)=><div className="tree" key={p.url}><b>{String(i+1).padStart(2,'0')}</b><div><strong>{p.title||p.path}</strong><span>{p.path}</span></div><small>{p.type}</small></div>)}</Panel>}
 {tab==='Pages'&&<div className="pages">{data.pages.map((p,i)=><article className="page" key={p.url}><small>PAGE {i+1}</small><h3>{p.title||'Untitled page'}</h3><a href={p.url} target="_blank" rel="noreferrer">{p.url}</a><p>{p.description||'No meta description found.'}</p><div className="mini"><span>{p.wordCount} words</span><span>{p.images.length} images</span><span>{p.internalLinks.length} internal links</span></div>{p.headings.h1[0]&&<blockquote>H1: {p.headings.h1[0]}</blockquote>}</article>)}</div>}
 {tab==='Links'&&<div className="grid"><Panel title={`Internal links (${internal.length})`}>{internal.map(x=><a className="row break" key={x} href={x} target="_blank" rel="noreferrer">{x}</a>)}</Panel><Panel title={`External links (${external.length})`}>{external.map(x=><a className="row break" key={x} href={x} target="_blank" rel="noreferrer">{x}</a>)}</Panel></div>}
 {tab==='Images'&&<Panel title={`Images (${imgs.length})`}><div className="images">{imgs.map(x=><a href={x} target="_blank" rel="noreferrer" key={x}><img src={x} loading="lazy" alt="Discovered website asset"/></a>)}</div></Panel>}
 {tab==='Technical'&&<div className="grid"><Panel title="Technical"><Info label="Origin" value={data.site.origin}/><Info label="robots.txt" value={data.robots.found?'Found':'Not found'}/><Info label="Sitemaps" value={data.robots.sitemaps.length||'None declared'}/><Info label="Skipped URLs" value={data.skipped.length}/></Panel><Panel title="Structured data">{[...new Set(data.pages.flatMap(p=>p.structuredDataTypes))].map(x=><span className="tag" key={x}>{x}</span>)}</Panel></div>}</section>}
 </Shell>
}
function Stat({n,t}){return <div><b>{n}</b><span>{t}</span></div>}
function Panel({title,children}){return <section className="panel"><h3>{title}</h3>{children}</section>}
function Info({label,value}){return <div className="info"><b>{label}</b><span className="break">{String(value)}</span></div>}
function Home(){return <Shell><section className="hero"><span className="eyebrow">WEBSITE INFORMATION, ORGANIZED</span><h1>See how a website is<br/><em>structured in seconds.</em></h1><p>Enter a public URL and SiteScope turns scattered website information into a clear report.</p><a className="cta" href="/website-analyzer">Analyze a website →</a></section><section className="cards"><Card icon={Network} title="Structure" text="Pages, paths and navigation."/><Card icon={FileText} title="Content outline" text="Titles, descriptions and headings."/><Card icon={Link2} title="Link map" text="Internal and external links."/><Card icon={Images} title="Images & metadata" text="Image URLs, canonicals and structured data."/></section></Shell>}
export default function App(){const p=window.location.pathname.replace(/\/+$/,'')||'/';if(p==='/website-analyzer')return <Analyzer/>;if(p==='/')return <Home/>;if(routes[p])return <StaticPage title={routes[p][0]} text={routes[p][1]}/>;return <StaticPage title="Page not found" text="Return to the SiteScope homepage or open the analyzer."/>}
