import express from 'express'
import * as cheerio from 'cheerio'
import ipaddr from 'ipaddr.js'
import robotsParser from 'robots-parser'
import dns from 'node:dns/promises'
import path from 'node:path'
import { fileURLToPath } from 'node:url'
import { readFile } from 'node:fs/promises'

const app = express()
const PORT = process.env.PORT || 8787
const USER_AGENT = 'SiteScopeBot/1.0'
const __dirname = path.dirname(fileURLToPath(import.meta.url))
const dist = path.resolve(__dirname, '../../client/dist')
app.use(express.json({limit:'100kb'}))

const buckets = new Map()
app.use('/api/analyze',(req,res,next)=>{const key=req.ip;const now=Date.now();const b=buckets.get(key)||{start:now,count:0};if(now-b.start>3600000){b.start=now;b.count=0}b.count++;buckets.set(key,b);if(b.count>30)return res.status(429).json({error:'Too many analyses. Please try again later.'});next()})

function normalizeInput(v){if(!v||typeof v!=='string')throw new Error('Enter a website URL.');let s=v.trim();if(!/^https?:\/\//i.test(s))s='https://'+s;const u=new URL(s);if(!['http:','https:'].includes(u.protocol))throw new Error('Only HTTP and HTTPS URLs are supported.');return u}
function privateIp(address){try{const a=ipaddr.parse(address);const r=a.range();return !['unicast'].includes(r)}catch{return true}}
async function assertPublic(url){const host=url.hostname.toLowerCase();if(host==='localhost'||host.endsWith('.local'))throw new Error('Local/private network addresses are not allowed.');const records=await dns.lookup(host,{all:true});if(!records.length||records.some(r=>privateIp(r.address)))throw new Error('Local/private network addresses are not allowed.')}
async function safeFetch(input,opts={}){let u=new URL(input);for(let i=0;i<5;i++){await assertPublic(u);const c=new AbortController();const timer=setTimeout(()=>c.abort(),12000);let r;try{r=await fetch(u,{...opts,redirect:'manual',signal:c.signal,headers:{'user-agent':USER_AGENT,'accept':'text/html,application/xhtml+xml,text/plain;q=.8,*/*;q=.2',...(opts.headers||{})}})}finally{clearTimeout(timer)}if([301,302,303,307,308].includes(r.status)){const loc=r.headers.get('location');if(!loc)throw new Error('Invalid redirect.');u=new URL(loc,u);continue}return {response:r,url:u}}throw new Error('Too many redirects.')}
function cleanText(s=''){return s.replace(/\s+/g,' ').trim()}
function pageType(pathname){if(pathname==='/'||pathname==='')return'home';const p=pathname.toLowerCase();if(p.includes('contact'))return'contact';if(p.includes('about'))return'about';if(p.includes('pricing'))return'pricing';if(p.includes('blog'))return'blog';if(p.includes('product'))return'product';if(p.includes('service'))return'service';return'page'}
function absolute(href,base){try{const u=new URL(href,base);if(!['http:','https:'].includes(u.protocol))return null;u.hash='';return u.toString()}catch{return null}}
function jsonLdTypes($){const out=[];$('script[type="application/ld+json"]').each((_,el)=>{try{const j=JSON.parse($(el).html()||'null');const walk=x=>{if(!x)return;if(Array.isArray(x))return x.forEach(walk);if(typeof x==='object'){if(x['@type'])Array.isArray(x['@type'])?out.push(...x['@type']):out.push(x['@type']);Object.values(x).forEach(walk)}};walk(j)}catch{}});return [...new Set(out)]}
function extract(html,url,origin){const $=cheerio.load(html);$('script:not([type="application/ld+json"]),style,noscript,template').remove();const internal=[],external=[],images=[],nav=[];$('a[href]').each((_,el)=>{const href=absolute($(el).attr('href'),url);if(!href)return;const u=new URL(href);const text=cleanText($(el).text())||href;if(u.origin===origin)internal.push(href);else external.push(href);if($(el).parents('nav,header').length&&u.origin===origin)nav.push({text,url:href})});$('img[src]').each((_,el)=>{const src=absolute($(el).attr('src'),url);if(src)images.push(src)});const canonical=absolute($('link[rel="canonical"]').attr('href')||'',url);const text=cleanText($('body').text());return{url,title:cleanText($('title').first().text()),description:cleanText($('meta[name="description"]').attr('content')||''),language:$('html').attr('lang')||'',canonical,headings:{h1:$('h1').map((_,x)=>cleanText($(x).text())).get().filter(Boolean),h2:$('h2').map((_,x)=>cleanText($(x).text())).get().filter(Boolean),h3:$('h3').map((_,x)=>cleanText($(x).text())).get().filter(Boolean)},internalLinks:[...new Set(internal)],externalLinks:[...new Set(external)],images:[...new Set(images)],navigation:nav,structuredDataTypes:jsonLdTypes($),wordCount:text?text.split(/\s+/).length:0,type:pageType(new URL(url).pathname)}}

app.get('/api/health',(req,res)=>res.json({ok:true}))
app.post('/api/analyze',async(req,res)=>{try{const start=normalizeInput(req.body.url);const maxPages=Math.min(20,Math.max(1,Number(req.body.maxPages)||10));await assertPublic(start);const origin=start.origin;let robots=null,robotsFound=false,sitemaps=[];try{const rr=await safeFetch(new URL('/robots.txt',origin));if(rr.response.ok){const txt=await rr.response.text();robots=robotsParser(new URL('/robots.txt',origin).toString(),txt);robotsFound=true;sitemaps=txt.split(/\r?\n/).map(x=>x.match(/^sitemap:\s*(.+)$/i)?.[1]?.trim()).filter(Boolean)}}catch{}
 const queue=[start.toString()],seen=new Set(),pages=[],skipped=[];while(queue.length&&pages.length<maxPages){const candidate=queue.shift();if(seen.has(candidate))continue;seen.add(candidate);const u=new URL(candidate);if(u.origin!==origin)continue;if(robots&&!robots.isAllowed(candidate,USER_AGENT)){skipped.push({url:candidate,reason:'Disallowed by robots.txt'});continue}try{const {response,url:finalUrl}=await safeFetch(candidate);if(!response.ok){skipped.push({url:candidate,reason:`HTTP ${response.status}`});continue}const ct=response.headers.get('content-type')||'';if(!ct.includes('text/html')){skipped.push({url:candidate,reason:'Not an HTML page'});continue}const html=await response.text();const p=extract(html,finalUrl.toString(),origin);pages.push(p);for(const link of p.internalLinks){if(queue.length+pages.length>80)break;if(!seen.has(link))queue.push(link)}}catch(e){skipped.push({url:candidate,reason:e.name==='AbortError'?'Timed out':e.message})}}
 if(!pages.length)throw new Error('No public HTML pages could be analyzed.');const home=pages[0];const navigation=[];for(const p of pages)for(const n of p.navigation)if(!navigation.some(x=>x.url===n.url))navigation.push(n);const emails=[],phones=[],socials=[];for(const p of pages){for(const l of [...p.internalLinks,...p.externalLinks]){if(l.startsWith('mailto:'))emails.push(l.slice(7));if(l.startsWith('tel:'))phones.push(l.slice(4));if(/facebook\.com|instagram\.com|linkedin\.com|youtube\.com|tiktok\.com|x\.com|twitter\.com/i.test(l))socials.push(l)}}
 const unique=a=>[...new Set(a)];res.json({analyzedAt:new Date().toISOString(),finalHomeUrl:home.url,site:{hostname:new URL(home.url).hostname,origin,title:home.title,description:home.description,language:home.language,canonical:home.canonical},totals:{pages:pages.length,internalLinks:unique(pages.flatMap(p=>p.internalLinks)).length,externalLinks:unique(pages.flatMap(p=>p.externalLinks)).length,images:unique(pages.flatMap(p=>p.images)).length,words:pages.reduce((n,p)=>n+p.wordCount,0)},navigation:navigation.slice(0,60),contacts:{emails:unique(emails),phones:unique(phones),socials:unique(socials)},robots:{found:robotsFound,url:new URL('/robots.txt',origin).toString(),sitemaps},structure:pages.map(p=>({url:p.url,path:new URL(p.url).pathname,title:p.title,type:p.type,wordCount:p.wordCount})),pages,skipped})}catch(e){res.status(400).json({error:e.message||'Could not analyze this website.'})}})

app.get('/robots.txt',(req,res)=>{const base=process.env.PUBLIC_ORIGIN||`${req.protocol}://${req.get('host')}`;res.type('text/plain').send(`User-agent: *\nAllow: /\nSitemap: ${base}/sitemap.xml\n`)})
app.get('/sitemap.xml',(req,res)=>{const base=process.env.PUBLIC_ORIGIN||`${req.protocol}://${req.get('host')}`;const paths=['/','/website-analyzer','/website-structure-analyzer','/website-link-analyzer','/how-it-works','/faq','/privacy','/terms'];res.type('application/xml').send(`<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">${paths.map(p=>`<url><loc>${base}${p}</loc></url>`).join('')}</urlset>`)})
app.use(express.static(dist,{extensions:['html']}))
app.get('*',async(req,res)=>{try{const route=req.path==='/'?'':req.path.replace(/^\//,'');const file=route?path.join(dist,route,'index.html'):path.join(dist,'index.html');let html=await readFile(file,'utf8').catch(()=>readFile(path.join(dist,'index.html'),'utf8'));const base=process.env.PUBLIC_ORIGIN||`${req.protocol}://${req.get('host')}`;html=html.replaceAll('__SITE_ORIGIN__',base);res.type('html').send(html)}catch{res.status(404).send('Not found')}})
app.listen(PORT,()=>console.log(`SiteScope running on ${PORT}`))
